### ISSUE TITLE
Multiple ways to build the same target were specified for ... wiring_pulse.o 

### ISSUE THREAD

**Issue by indrekluuk** [platformio/platformio-pkg-framework-arduinoavr#13]
After doing "platformio update" my code does not compile anymore.
It seems to be arduinoavr specific problem.

I get this error:
*** Multiple ways to build the same target were specified for: C:\development\microcontrollers\Arduino\experiments\LiveOV7670\src\.pioenvs\nanoatmega328\FrameworkArduino\wiring_pulse.o  (from ['C:\\Users\\indrek\\.platformio\\packages\\framework-arduinoavr\\cores\\arduino\\wiring_pulse.S'] and from ['C:\\Users\\indrek\\.platformio\\packages\\framework-arduinoavr\\cores\\arduino\\wiring_pulse.c'])
File "C:\python27\lib\site-packages\platformio\builder\tools\platformio.py", line 275, in BuildLibrary

platformio.ini looks like this:
[platformio]
```
src_dir = LiveOV7670

[env:nanoatmega328]
platform = atmelavr
framework = arduino
board = nanoatmega328

```

I initialized the project for CLion with 
platformio init -d src --ide clion
(platformio.ini is in the "src" directory)

It worked before updating platformIO and my other project that uses STM32 still works

**Comment by ivankravets** [comment]
You need to upgrade PIO Core and development platforms. 

`pio update`
`pio upgrade`

**Comment by indrekluuk** [comment]
Thanks! This helped.
