### ISSUE TITLE
Update controllino mega variant

### ISSUE THREAD

**Issue by sunbit** [platformio/platformio-pkg-framework-arduinoavr#17]
As added in 9-Nov-2018, owners of Controllino Mega now need to do a manual patch as described here):

https://github.com/CONTROLLINO-PLC/CONTROLLINO_Library/commit/b86c8f4c68be2062d90ba1bc50d3a0514039558a#diff-04c6e90faac2675aa89e2176d2eec7d8

in order to keep using platformio. To avoid the need to do this hack, I wonder if such changes (that are made into the mega/pins_arduino.h) could be integrated in the controllino mega variant file here:

https://github.com/platformio/platformio-pkg-framework-arduinoavr/blob/master/variants/Controllino_mega/pins_arduino.h

Not sure on where to find this file online, it seems that this is generated by the Arduino IDE? I attach the one i have installed right now as a reference (changed extension to be able to upload it):

[pins_arduino.h.txt](https://github.com/platformio/platformio-pkg-framework-arduinoavr/files/2776459/pins_arduino.h.txt)

I'm not sure if pull requests are accepted in this repo, if so i can try it myself and test it with my Controllino Mega.

**Comment by ivankravets** [comment]
Resolved in:

- https://github.com/platformio/platformio-pkg-framework-arduinoavr/commit/5e536edab9eca203cfb23ca388c5582c3f6c1381
- https://github.com/platformio/platformio-pkg-framework-arduinoavr/commit/1425864de6adaec9d3abb8dc231bc53733d600d7

Please open PlatformIO IDE => Terminal and type
```
pio update
```

Does it work now without any modifications?

**Comment by sunbit** [comment]
yes, it works now, current versions:

Updating framework-arduinoavr            @ 1.10623.2      [1.10623.190125]
PlatformIO has been successfully upgraded to 3.6.4!

Thank you!

**Comment by ivankravets** [comment]
Thanks!
