### ISSUE TITLE
Cant find stdlib.h or inttypes.h in build process

### ISSUE THREAD

**Issue by LiamLombard** [platformio/platformio-pkg-framework-arduinoavr#2]
Hi
Sorry for the bother but just came across this and couldnt figure out how to solve it.
Not sure if i've done something wrong or if its a bug but heres the terminal output when attempting to build a simple blink example:

`[01/19/17 22:57:25] Processing uno (platform: atmelavr, board: uno, framework: arduino)
 
Verbose mode can be enabled via `-v, --verbose` option
Collected 27 compatible libraries
Looking for dependencies...
Project does not have dependencies

Compiling .pioenvs\uno\src\main.o
Archiving .pioenvs\uno\libFrameworkArduinoVariant.a
Compiling .pioenvs\uno\FrameworkArduino\CDC.o
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial.o
Indexing .pioenvs\uno\libFrameworkArduinoVariant.a
In file included from src\main.cpp:7:0:
C:\users\cwpf69\.platformio\packages\framework-arduinoavr\cores\arduino/Arduino.h:23:20: fatal error: stdlib.h: No such file or directory
#include <stdlib.h>
^
compilation terminated.
*** [.pioenvs\uno\src\main.o] Error 1
In file included from C:\users\cwpf69\.platformio\packages\framework-arduinoavr\cores\arduino\CDC.cpp:19:0:
C:\users\cwpf69\.platformio\packages\framework-arduinoavr\cores\arduino\USBAPI.h:23:22: fatal error: inttypes.h: No such file or directory
#include <inttypes.h>
^
compilation terminated.
C:\users\cwpf69\.platformio\packages\framework-arduinoavr\cores\arduino\HardwareSerial.cpp:25:20: fatal error: stdlib.h: No such file or directory
#include <stdlib.h>
^
compilation terminated.
*** [.pioenvs\uno\FrameworkArduino\CDC.o] Error 1
*** [.pioenvs\uno\FrameworkArduino\HardwareSerial.o] Error 1
 [ERROR] Took 0.96 seconds`

**Comment by ivankravets** [comment]
1. Please use http://community.platformio.org/
2. Try to delete folder `C:\users\cwpf69.platformio` and build again
