### ISSUE TITLE
Not able to compile MightyCore targets due to a silly bug.

### ISSUE THREAD

**Issue by MCUdude** [platformio/platformio-pkg-framework-arduinoavr#20]
Hi!

I have the following platformio.ini file:
``` ini
[env:MightyCore]
platform = atmelavr
framework = arduino

; TARGET SETTINGS
; PlatformIO requires the board parameter. Must match your actual hardware
board = ATmega1284P
```

The problem is that with this configuration I can't compile for anything else than the ATmega324PB, due to a silly bug. The problem is that SPI1.h is automatically included. I don't know why, but that's what's happening. It can easily be fixed by removing [these lines of code](https://github.com/platformio/platformio-pkg-framework-arduinoavr/blob/204dd4b5defa7ef538e18650207803def358d1fa/libraries/__cores__/MightyCore/SPI/src/SPI.h#L19-L21). Here is a [related issue](https://github.com/MCUdude/MightyCore/issues/140) as well.

I assume you prefer a new release of MightyCore with this bug fixed? Or can the PlatformIO build script be modified to not include the file?

**Comment by ivankravets** [comment]
See https://github.com/MCUdude/MightyCore/pull/158
