### ISSUE TITLE
Update ATTinyCore to 1.3.2

### ISSUE THREAD

**Issue by stonehippo** [platformio/platformio-pkg-framework-arduinoavr#23]
The current version of ATTinyCore embedded here is 1.2.2, which is pretty old. As mentioned in https://github.com/platformio/platform-atmelavr/issues/83, this should get updated to the latest version, 1.3.2.

See https://github.com/SpenceKonde/ATTinyCore/releases/tag/1.3.2 for details on the latest 1.3.2 release.

**Comment by stonehippo** [comment]
@ivankravets I’ll see if I can find some time to create a PR to cover this update.

**Comment by ivankravets** [comment]
:) https://github.com/platformio/platformio-pkg-framework-arduinoavr/pull/24
