### ISSUE TITLE
Request to remove RobotIRemote library

### ISSUE THREAD

**Issue by z3t0** [platformio/platformio-pkg-framework-arduinoavr#6]
Hi I am the maintainer of Arduino-IRremote (originally written by Ken Shirriff) and I run into a lot of issues with automated CI and also just users in general as the library I maintain conflicts with RobotIRremote.

I have created an issue on the arduino/libraries repository but have not received any responses. I would like to make the request that the RobotIRremote library be removed as it is based on a very old fork of Arduino-IRremote and prevents newer releases from functioning due to similar file naming conventions.

Thanks!

**Comment by ivankravets** [comment]
Thanks, I've just removed! The release package will be re-packed later and release with a new `atmelavr` development platform.

PIO support multiple library storages and has different priorities between them. See http://docs.platformio.org/en/latest/librarymanager/ldf.html#storage

You can use `pio lib -g install IRremote` to install library into the global or add a dependency to a project:
```ini
[env:...]
...
framework = arduino
lib_deps = IRremote
...
```

In this case, PIO will use the latest IRremote version.
